### PR TITLE
fix #88 avoid loading null fields to Redis Hash

### LINKED ISSUE #88: Read through fails to read rows with NULL values
If a row in the database contains a null value for some column that does not have not-null property set to true (meaning that it can have a null value), read through fails to read that row.
to reproduce, insert a row that have a null value for some property, then try "hgetall <key>".
The command returns:
(empty array)

The RG.GETEXUCUTION output show:
1) 1) "shard_id"
   2) "0000000000000000000000000000000000000144"
   3) "execution_plan"
   4)  1) "status"
       2) "done"
       3) "shards_received"
       4) (integer) 0
       5) "shards_completed"
       6) (integer) 0
       7) "results"
       8) (integer) 0
       9) "errors"
      10) 1) "java.lang.NullPointerException|\tat com.redislabs.PropertyData.convertToStr(PropertyData.java:64)|\tat com.redislabs.ReadSource.foreach(ReadSource.java:87)|\tat com.redislabs.ReadSource.foreach(ReadSource.java:18)|"
      11) "total_duration"
      12) (integer) 1221
      13) "read_duration"
      14) (integer) 0
      15) "steps"
      16) 1) 1) "type"
             2) "foreach"
             3) "duration"
             4) (integer) 0
             5) "name"
             6) "JVM_Foreach"
             7) "arg"
             8) "java object"
          2) 1) "type"
             2) "map"
             3) "duration"
             4) (integer) 0
             5) "name"
             6) "JVM_ToJavaRecordMapper"
             7) "arg"
             8) ""

It looks like it throws an exception when trying to convert the null value to string. It should ignore a null value.

### PR DESCRIPTION
**Pull request by gkorland**
1. Avoid loading null fields to Redis
2. Reply should return `nil` if specific list of field was requested

### CODE REVIEW

File: src/main/java/com/redislabs/ReadSource.java [hunk 1]
```diff
@@ -82,9 +82,11 @@ public void foreach(KeysReaderRecord r) throws Exception {
           GearsBuilder.overrideReply(error);
           throw new Exception(error);
         }
-        command.add(propKey);
-        Object value = e.getValue();
-        command.add(pd.convertToStr(value));
+        if (value != null) {
+          command.add(propKey);
+          Object value = e.getValue();
```
Comment (MeirShpilraien) [inline src/main/java/com/redislabs/ReadSource.java:87]: Get this line out of the if statement?

File: src/main/java/com/redislabs/ReadSource.java [hunk 2]
```diff
@@ -131,16 +133,22 @@ public void foreach(KeysReaderRecord r) throws Exception {
             GearsBuilder.overrideReply(error);
             throw new Exception(error);
           }
-          response.add(propKey);
-          Object value = e.getValue();
-          response.add(pd.convertToStr(value));
+          if (value != null){
+            response.add(propKey);
+            Object value = e.getValue();
```
Comment (MeirShpilraien) [inline src/main/java/com/redislabs/ReadSource.java:138]: Same

File: src/main/java/com/redislabs/ReadSource.java (hunk 1 above)
Comment (MeirShpilraien) [reply src/main/java/com/redislabs/ReadSource.java:87]: Also maybe we do want to add an empty value on this field?

File: src/main/java/com/redislabs/ReadSource.java [hunk 3]
```diff
@@ -131,16 +133,22 @@ public void foreach(KeysReaderRecord r) throws Exception {
...
         for(String f : fields) {
           if(res.containsKey(f)) {
             PropertyData pd = getPropertyMapping(f);
             Object value = res.get(f);
-            response.add(pd != null ? pd.convertToStr(value) : value.toString());
+            if( value == null) {
+              response.add(null);
+            } else {
+              response.add(pd != null ? pd.convertToStr(value) : value.toString());
+            }
```
Comment (MeirShpilraien) [inline src/main/java/com/redislabs/ReadSource.java:151]: Here you return a NULL response, so either add an empty field on above and return here an empty field or do not return this field at all, otherwise you will have inconsistency with cache hit that will come after and will actually performs the hget command.

**Review by MeirShpilraien — COMMENTED** [review]
We should add a test no?

**Comment by gkorland** [comment]
Sure, just a draft

File: src/main/java/com/redislabs/ReadSource.java (hunk 1 above)
Comment (gkorland) [reply src/main/java/com/redislabs/ReadSource.java:87]: Don't think so, there is a different between null and empty string

Comment (MeirShpilraien) [reply src/main/java/com/redislabs/ReadSource.java:87]: Look at the comment bellow then, we should not return this field at all then ...

Comment (gkorland) [reply src/main/java/com/redislabs/ReadSource.java]: right this is why I added `command.add(propKey);` to the if part

File: src/main/java/com/redislabs/ReadSource.java (hunk 3 above)
Comment (gkorland) [reply src/main/java/com/redislabs/ReadSource.java:151]: I return the Null response to for consistency.
This is the case when the use gave an explicit list of fields using `HMGET` in this case for each field missing Redis returns `nil`

Comment (MeirShpilraien) [reply src/main/java/com/redislabs/ReadSource.java:151]: Ohh ok :+1:

**Review by MeirShpilraien — APPROVED** [review]
:+1:
